# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 16:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('castar', '0004_starphotos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='starphotos',
            options={'verbose_name_plural': 'Star Photos'},
        ),
    ]
